export enum HealthRecordType {
    LAB_REPORT = 'LAB_REPORT',
    PRESCRIPTION = 'PRESCRIPTION',
    DISCHARGE_SUMMARY = 'DISCHARGE_SUMMARY',
    DIAGNOSTIC_REPORT = 'DIAGNOSTIC_REPORT',
    OPD_RECORD = 'OPD_RECORD',
    IMMUNIZATION_RECORD = 'IMMUNIZATION_RECORD',
    WELLNESS_RECORD = 'WELLNESS_RECORD'
} 