export enum HealthRecordType {
  PRESCRIPTION = 'PRESCRIPTION',
  DIAGNOSIS = 'DIAGNOSIS',
  LAB_REPORT = 'LAB_REPORT',
  IMAGING_REPORT = 'IMAGING_REPORT',
  DISCHARGE_SUMMARY = 'DISCHARGE_SUMMARY',
  OPD_NOTE = 'OPD_NOTE',
  VACCINATION = 'VACCINATION',
  ALLERGY = 'ALLERGY',
  MEDICAL_HISTORY = 'MEDICAL_HISTORY',
  VITAL_SIGN = 'VITAL_SIGN',
  PROCEDURE = 'PROCEDURE',
  OTHER = 'OTHER'
} 